name: jogar
description: "Three in a row game."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  flutter_inappwebview: ^5.8.0
  animated_text_kit: ^4.2.2
  hive_flutter: ^1.1.0
  audioplayers: ^5.2.1
  parse_server_sdk_flutter:
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  image_path: "assets/images/app_logo/logo.png"
  
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/background/png/
    - assets/images/background/svg/
    - assets/images/button/
    - assets/images/icons/png/
    - assets/images/icons/svg/
    - assets/sound/effects/
    - assets/sound/theme/

  fonts:
    - family: "Changa"
      fonts:
        - asset: assets/fonts/changa/w200.ttf
          weight: 200
        - asset: assets/fonts/changa/w300.ttf
          weight: 300
        - asset: assets/fonts/changa/w400.ttf
          weight: 400
        - asset: assets/fonts/changa/w500.ttf
          weight: 500
        - asset: assets/fonts/changa/w600.ttf
          weight: 600
        - asset: assets/fonts/changa/w700.ttf
          weight: 700
        - asset: assets/fonts/changa/w800.ttf
          weight: 800
    - family: "Nerko"
      fonts:
        - asset: assets/fonts/nerko/nerko_one.ttf